main: com.mortuusterrachat.MortuusTerraChat
name: MortuusTerraChat
version: 1.0
author: kadeska233
depends: [MortuusTerraCore]
softdepend: []
database: false
description: >
             Chat-AddOn for the Mortuus Terra survival server.
             Additional Modules:
             Features:
                 - Walkie Talkies
                 - Cellular Phones
                 - Scrambled Messages
                 - Broadcasting
commands:
  mtr:
    usage: /mtr
    description: Use /mtr for help.

permissions:
  mtcom.unscrambled:
    description: Send an unscrambled message to everyone online.
    default: op